// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An activity log entry in a full snapshot. Faithful to
 * `syncode_orchestration::ActivityView`.
 */
export type ActivitySummary = { id: string, activity_type: string, description: string, project_id: string | null, thread_id: string | null, metadata: Record<string, unknown>, created_at: string, };
