// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An activity log entry in a full snapshot. Faithful to
 * `syncode_orchestration::ActivityView`.
 */
export type ActivitySummary = { id: string, activityType: string, description: string, projectId: string | null, threadId: string | null, metadata: Record<string, unknown>, createdAt: string, };
