// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `auth/logout` result.
 */
export type AuthLogoutResult = { loggedOut: boolean, 
/**
 * `true` if the connection had a session before logout.
 */
hadSession: boolean, };
