// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `auth/status` result — the connection's current auth state.
 *
 * Pre-auth in requiring mode: `{ authenticated: false, requiresAuthentication:
 * true, role: null, subject: null }` (no `expiresAt`). Authenticated: full set.
 */
export type AuthStatusResult = { authenticated: boolean, requiresAuthentication: boolean, 
/**
 * Role string when authenticated; `null` otherwise.
 */
role?: string, 
/**
 * Subject string when authenticated; `null` otherwise.
 */
subject?: string, 
/**
 * Expiry when authenticated; absent otherwise.
 */
expiresAt?: string, };
