// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `auth/bootstrap` params: `{ credential }`.
 */
export type AuthBootstrapParams = { 
/**
 * Bearer credential / shared secret. Opaque to the client.
 */
credential: string, };
