// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `auth/bootstrap` result. Shape differs by auth mode:
 * - **No-auth mode:** `{ authenticated, mode, note }` (no token/role/subject).
 * - **Requiring mode:** `{ authenticated, sessionToken, role, subject, expiresAt }`.
 *
 * The `sessionToken`/`role`/`subject`/`expiresAt` fields are all optional so
 * the same DTO covers both shapes; the no-auth variant just leaves them unset.
 */
export type AuthBootstrapResult = { 
/**
 * Always `true` on success.
 */
authenticated: boolean, 
/**
 * Auth mode string echoed from `WsAuthConfig.mode` (e.g. "none", "remote").
 */
mode: string, 
/**
 * Human-readable note (only set in no-auth mode).
 */
note?: string, 
/**
 * Bearer session token (only in requiring mode).
 */
sessionToken?: string, 
/**
 * Principal role (only in requiring mode). E.g. "owner", "operator", "viewer".
 */
role?: string, 
/**
 * Principal subject identifier (only in requiring mode).
 */
subject?: string, 
/**
 * ISO-8601 expiry timestamp (only in requiring mode).
 */
expiresAt?: string, };
