// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file in a turn-diff checkpoint summary (mcode `OrchestrationCheckpointFile`).
 * Mirrors `syncode_core::domain::events::CheckpointFile` for the
 * `TurnDiffCompleted` payload.
 */
export type CheckpointFileDto = { path: string, kind: string, additions: number, deletions: number, };
