// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateSessionRequest = { provider_id: string, model: string, working_directory: string | null, };
