// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivitySummary } from "./ActivitySummary";
import type { MessageSummary } from "./MessageSummary";
import type { ProjectSummary } from "./ProjectSummary";
import type { SnapshotScope } from "./SnapshotScope";
import type { ThreadSummary } from "./ThreadSummary";
import type { TurnSummary } from "./TurnSummary";

/**
 * Full-store snapshot — every collection. Sent on `*` wildcard subscribe.
 */
export type FullSnapshot = { scope: SnapshotScope, projects: Array<ProjectSummary>, threads: Array<ThreadSummary>, turns: Array<TurnSummary>, messages: Array<MessageSummary>, activities: Array<ActivitySummary>, snapshot_at: string, };
