// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileStatusKind } from "./FileStatusKind";

export type GitFileStatusView = { path: string, indexStatus: FileStatusKind, workingTreeStatus: FileStatusKind, };
