// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitFileStatusView } from "./GitFileStatusView";

export type GitStatusView = { branch: string | null, headDetached: boolean, files: Array<GitFileStatusView>, ahead: number, behind: number, };
