// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonRpcRequestView = { jsonrpc: string, id?: string, method: string, params?: Record<string, unknown>, };
