// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonRpcErrorView } from "./JsonRpcErrorView";

export type JsonRpcResponseView = { jsonrpc: string, id?: string, result?: Record<string, unknown>, error?: JsonRpcErrorView, };
