// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JsonRpcErrorView = { code: number, message: string, data?: Record<string, unknown>, };
