// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `rpc/listMethods` — the enumeration of methods this server serves.
 * Mirrors the `{"methods": [...]}` object emitted by `dispatch_method`.
 */
export type ListMethodsResult = { methods: Array<string>, };
