// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A message in a thread-detail snapshot. Faithful to
 * `syncode_orchestration::MessageView` (NOT the contracts `MessageView`, which
 * is a different, session-oriented type).
 */
export type MessageSummary = { id: string, turnId: string, role: string, content: string, contentType: string, tokenCount: number | null, toolName: string | null, toolCallId: string | null, createdAt: string, isStreaming: boolean, };
