// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { MessageRole } from "./MessageRole";
import type { Timestamp } from "./Timestamp";

export type MessageView = { id: EntityId, role: MessageRole, content: string, timestamp: Timestamp, };
