// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A message in a thread-detail snapshot. Faithful to
 * `syncode_orchestration::MessageView` (NOT the contracts `MessageView`, which
 * is a different, session-oriented type).
 */
export type MessageSummary = { id: string, turn_id: string, role: string, content: string, content_type: string, token_count: number | null, tool_name: string | null, tool_call_id: string | null, created_at: string, is_streaming: boolean, };
