// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `ping` — an empty object. (Modeled as a struct rather than `()`
 * so the TS registry has a concrete `Result` type per method.)
 */
export type PingResult = Record<string, never>;
