// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `project/create` params: `{ name, rootPath }`.
 */
export type ProjectCreateParams = { 
/**
 * Human-readable project name. Must be non-empty (handler rejects whitespace).
 */
name: string, 
/**
 * Absolute filesystem path to the project root.
 */
rootPath: string, };
