// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project's key fields, as carried in a snapshot. Faithful to
 * `syncode_orchestration::ProjectView` (slimmed to the fields a client needs
 * for shell/list views).
 */
export type ProjectSummary = { id: string, name: string, rootPath: string, providerId: string | null, defaultModel: string | null, createdAt: string, updatedAt: string, threadCount: number, };
