// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `project/get` params: `{ id }`.
 */
export type ProjectGetParams = { 
/**
 * Project identifier (UUID string).
 */
id: string, };
