// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A project's key fields, as carried in a snapshot. Faithful to
 * `syncode_orchestration::ProjectView` (slimmed to the fields a client needs
 * for shell/list views).
 */
export type ProjectSummary = { id: string, name: string, root_path: string, provider_id: string | null, default_model: string | null, created_at: string, updated_at: string, thread_count: number, };
