// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";

/**
 * `project/list` — no params. Result is `{ projects: ProjectSummary[] }`.
 *
 * The handler serializes `read_store.projects.values()` directly; the view's
 * shape matches `ProjectSummary` (id, name, rootPath, providerId, …).
 */
export type ProjectListResult = { projects: Array<ProjectSummary>, };
