// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderConfig = { id: string, apiKey: string, baseUrl: string | null, model: string | null, maxTokens: number | null, temperature: number | null, };
