// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderCapabilities = { chat: boolean, edit: boolean, vision: boolean, function_calling: boolean, streaming: boolean, };
