// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProviderConfig = { id: string, api_key: string, base_url: string | null, model: string | null, max_tokens: number | null, temperature: number | null, };
