// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `push/subscribe` params: `{ channel, threadId? }`.
 *
 * `channel` is one of the known push channels (`"orchestration"`, `"git"`,
 * `"terminal"`, or `"*"`). `threadId` is an optional selector for the
 * `orchestration` channel: when set, the snapshot is thread-detail (one
 * thread + turns + messages) instead of the shell-wide snapshot.
 */
export type PushSubscribeParams = { 
/**
 * Push channel name (`"orchestration"`, `"git"`, `"terminal"`, or `"*"`).
 */
channel: string, 
/**
 * Optional thread selector for the orchestration channel snapshot scope.
 */
threadId?: string, };
