// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `push/subscribe` result.
 */
export type PushSubscribeResult = { subscribed: boolean, 
/**
 * Echoed channel name.
 */
channel: string, 
/**
 * `true` if this call created a new subscription (idempotent — re-subscribe is `false`).
 */
added: boolean, 
/**
 * `true` if a snapshot was emitted to this connection (snapshot-then-stream).
 */
snapshotEmitted: boolean, };
