// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Timestamp } from "./Timestamp";

export type PushEvent = { channel: string, event_type: string, data: Record<string, unknown>, timestamp: Timestamp, };
