// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `push/unsubscribe` params: `{ channel }`. `"*"` clears all subscriptions.
 */
export type PushUnsubscribeParams = { channel: string, };
