// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `push/unsubscribe` result.
 */
export type PushUnsubscribeResult = { unsubscribed: boolean, channel: string, 
/**
 * `true` if a subscription was actually removed.
 */
removed: boolean, };
