// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityId } from "./EntityId";
import type { SessionStatus } from "./SessionStatus";
import type { Timestamp } from "./Timestamp";

export type SessionView = { id: EntityId, providerId: string, model: string, workingDirectory: string | null, createdAt: Timestamp, status: SessionStatus, };
