// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";
import type { SnapshotScope } from "./SnapshotScope";
import type { ThreadSummary } from "./ThreadSummary";

/**
 * Shell-channel snapshot — projects + threads. Sent on `orchestration`
 * channel subscribe (when no `threadId` is given).
 */
export type ShellSnapshot = { scope: SnapshotScope, projects: Array<ProjectSummary>, threads: Array<ThreadSummary>, 
/**
 * ISO-8601 timestamp at which the snapshot was read.
 */
snapshot_at: string, };
