// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The scope a snapshot covers. Carried in every snapshot envelope so the
 * client knows which of the snapshot DTOs to decode `data` as.
 */
export type SnapshotScope = "shell" | "thread" | "full";
