// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `thread/list` params: `{ projectId? }`. Empty/unset projectId returns all.
 */
export type ThreadListParams = { 
/**
 * Optional filter: only threads belonging to this project. Empty string
 * or omitted means "all threads" (matches handler's `project_id.is_empty()`).
 */
projectId?: string, };
