// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadSummary } from "./ThreadSummary";

/**
 * `thread/list` result — `{ threads: ThreadSummary[] }`.
 */
export type ThreadListResult = { threads: Array<ThreadSummary>, };
