// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A thread's key fields, as carried in a snapshot. Faithful to
 * `syncode_orchestration::ThreadView`.
 */
export type ThreadSummary = { id: string, projectId: string, providerId: string, model: string, status: string, title: string | null, gitCheckpoint: string | null, runtimeMode: string, interactionMode: string, turnCount: number, createdAt: string, updatedAt: string, };
