// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A thread's key fields, as carried in a snapshot. Faithful to
 * `syncode_orchestration::ThreadView`.
 */
export type ThreadSummary = { id: string, project_id: string, provider_id: string, model: string, status: string, title: string | null, git_checkpoint: string | null, runtime_mode: string, interaction_mode: string, turn_count: number, created_at: string, updated_at: string, };
