// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `thread/create` params: `{ projectId, providerId, model }`.
 */
export type ThreadCreateParams = { 
/**
 * Parent project's UUID.
 */
projectId: string, 
/**
 * Provider identifier (e.g. "anthropic").
 */
providerId: string, 
/**
 * Model slug (e.g. "claude-sonnet-4").
 */
model: string, };
