// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageSummary } from "./MessageSummary";
import type { SnapshotScope } from "./SnapshotScope";
import type { ThreadSummary } from "./ThreadSummary";
import type { TurnSummary } from "./TurnSummary";

/**
 * Thread-detail snapshot — one thread + its turns + messages. Sent on
 * `orchestration` channel subscribe when a `threadId` is given.
 */
export type ThreadDetailSnapshot = { scope: SnapshotScope, thread: ThreadSummary, turns: Array<TurnSummary>, messages: Array<MessageSummary>, snapshotAt: string, };
