// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnSummary } from "./TurnSummary";

/**
 * `turn/list` result — `{ turns: TurnSummary[] }`.
 */
export type TurnListResult = { turns: Array<TurnSummary>, };
