// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A turn's key fields, as carried in a thread-detail snapshot. Faithful to
 * `syncode_orchestration::TurnView`.
 */
export type TurnSummary = { id: string, threadId: string, sequence: number, userInput: string, assistantOutput: string | null, status: string, gitCheckpoint: string | null, filesModified: Array<string>, durationMs: number | null, createdAt: string, completedAt: string | null, };
