// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `turn/start` params: `{ threadId, sequence?, userInput }`.
 */
export type TurnStartParams = { 
/**
 * Parent thread's UUID.
 */
threadId: string, 
/**
 * Optional sequence number; defaults to 0 if absent (handler coerces u32).
 */
sequence?: number, 
/**
 * The user's prompt text for this turn.
 */
userInput: string, };
