// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `turn/complete` params: `{ id, assistantOutput, durationMs? }`.
 */
export type TurnCompleteParams = { 
/**
 * The turn to complete (UUID).
 */
id: string, 
/**
 * The assistant's response text.
 */
assistantOutput: string, 
/**
 * Wall-clock duration in milliseconds. Defaults to 0 if absent.
 */
durationMs: number | null, };
